food/urls.py
from django.conf.urls import url
from . import views

app_name='food'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^(?P<post_id>[0-9]+)/vote$', views.vote, name="vote"),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.comment, name='comment'),

]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^food/', include('food.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    people = models.IntegerField(default=3)
    budget = models.IntegerField(default=12)
    image=models.FileField(null=True, blank=True)
    ingredients = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class Choice(models.Model):
    choice_text= models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)


class Comment(models.Model):
    text = models.CharField(max_length=200)
    user = models.CharField(max_length=20)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)

food/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post, Choice, Comment
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .froms import PostForm, CommentForm
from django.contrib.auth.models import User


def home(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    context = {'posts': posts}
    query = request.GET.get("q")
    if query:
        posts = posts.filter(title__icontains=query)
        context = {'posts': posts}
    return render(request, 'food/home.html', context)


def detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    return render(request, 'food/detail.html', {'post': post})


def vote(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    try:
        selected_choice = post.choice_set.get(pk=request.POST['choice'])
    except:
        return render(request, 'food/detail.html', {'post': post, 'error message': "Please select a choice"})
    selected_choice.votes += 1
    selected_choice.save()
    return HttpResponseRedirect(reverse('food:detail', args=(post.id,)))


def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = User.objects.get(username="anonymous")
            post.published_date = timezone.now()
            post.save()
            choice1 = Choice.objects.create(choice_text='1', post=post)
            choice1.save()
            choice2 = Choice.objects.create(choice_text='2', post=post)
            choice2.save()
            choice3 = Choice.objects.create(choice_text='3', post=post)
            choice3.save()
            choice4 = Choice.objects.create(choice_text='4', post=post)
            choice4.save()
            choice5 = Choice.objects.create(choice_text='5', post=post)
            choice5.save()
            return redirect('http://127.0.0.1:8000/food/', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'food/post_edit.html', {'form': form})


def comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return HttpResponseRedirect(reverse('food:detail', args=(post.id,)))
    else:
        form = CommentForm()
    return render(request, 'food/comment.html', {'form': form})

food/templates/food/comment.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>upload of recipe </title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- CSS file made by the group -->
        <link href="style-3.css" rel="stylesheet">
    </head>

    <body class="body3">





        <div class="container">
            <div class="col-lg-10 col-lg-offset-1">
                <nav class="navbar navbar-inverse ">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand"  href="FirstPage.html">Home</a>
                        </div>

                        <div class="collapse navbar-collapse" id="navbar-collapse-1">
                           <div class="hidden-sm col-md-5">
                                <form class="navbar-form navbar-left" style="margin-left: 5%;" method="GET" action="">
                                <div class="input-group">
                                      <input type="text" class="form-control" placeholder="Recipe..." name="q">
                                      <div class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">Search</button>
                                      </div>
                                </div>
                                </form>
                            </div>
                      </div>
                 </div>
                  </nav>


<form method="POST" class="post-form">{% csrf_token %}
                  <div class="col-md-8 comment-recipe">
                    <div class="form-group">

                      <label for="id_title">Title</label>
                      {{form.user}}
                    </div>
                   <div class="form-group">
                     <label for="exampleTextarea">write your comment:</label>
                     {{form.text}}
                   </div>
                   <button type="submit" class="btn btn-primary" >comment</button>
                 </div>
</form>

    </body>
</html>

food/templates/food/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>Name and details of recipe</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

		<!-- Scripts for this page -->
		<script src="ThirdPage.js" type="text/javascript"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- CSS file made by the group -->
        <link href="foodapp/mysite/food/static/css/style-3.css" rel="stylesheet">
    </head>

    <body class="body3">

      <div class="container">
          <div class="col-lg-10 col-lg-offset-1">
      <nav class="navbar navbar-inverse ">
                         <div class="container-fluid">
                             <div class="navbar-header">



                                 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                                     <span class="sr-only">Toggle navigation</span>
                                     <span class="icon-bar"></span>
                                     <span class="icon-bar"></span>
                                     <span class="icon-bar"></span>

                                 </button>
                                 <a class="navbar-brand"  href="FirstPage.html">Home</a>
                             </div>

                             <div class="collapse navbar-collapse" id="navbar-collapse-1">
                                 <div class="hidden-sm col-md-5">
                                     <form class="navbar-form navbar-left" style="margin-left: 5%;" method="GET" action="">
                                         <div class="input-group">
                                             <input type="text" class="form-control" placeholder="Search for other recipes" name="q">
                                             <div class="input-group-btn">
                                                 <button type="submit" class="btn btn-primary" >Search</button>
                                             </div>
                                         </div>
                                     </form>
                                 </div>
                                 <ul class="nav navbar-nav navbar-right">


                                     <li><a href="upload.html">New recipe</a></li>


                                  </ul>
                             </div>
                         </div>
                     </nav>




		<div class="container title">
			<h1 class="titleHeader" id="header">{{post.title}}</h1>
		</div>
		
         <div class="row">
            <div class="col-sm-4 content-recipe">
                <img src="{{post.image.url}}">
            </div>
            <div class="col-sm-4 content-recipe">
                <a href="" id="recipe-url">Click here to go to publisher page and show the recipe description</a>
				
            </div>
        </div>

         <div class="recipe-info">
                <div class="col-sm-4 ingredient-box">
                    <ul id="recipe-ingredients">{{post.ingredients}}</ul>
					
                </div>
                <div class="col-sm-4 budget-box">
                    <p>Budget: {{post.budget}}</p>
                </div>
                <div class="col-sm-4 recipe-description-box">
                    <p>Number of people: {{post.people}}</p>
                </div>
        </div>
<hr>
<form action="{% url 'food:vote' post.id %}" method="post">
    {% csrf_token %}
    {% for choice in post.choice_set.all %}
    <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
    <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label>
    <label for="choice{{forloop.counter}}"> votes: {{choice.votes}}</label>
    {% endfor %}
    <input type="submit" value="vote"/>
</form>
<hr>
          <div class="comment-button">
          <a class="btn btn-default" href="{% url 'food:comment' pk=post.pk %}">Add comment</a>
{% for comment in post.comment_set.all %}
        <strong>{{ comment.user }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
        </div>

      </div>

        </div>
    </body>
</html>

food/templates/food/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>List of recipes</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		
		<!-- Scripts for this page -->
		<script src="SecondPage.js" type="text/javascript"></script>
		
        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- CSS file made by the group -->
        <link href="style-2.css" rel="stylesheet">

    </head>

    <body class='body2'>

      <div class="container">
          <div class="col-lg-10 col-lg-offset-1">
      <nav class="navbar navbar-inverse ">
            <div class="container-fluid">
                <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>

                </button>

                <a class="navbar-brand"  href="FirstPage.html">Home</a>



                             </div>

                             <div class="collapse navbar-collapse" id="navbar-collapse-1">
                                 <div class="hidden-sm col-md-5">
                                     <form class="navbar-form navbar-left" style="margin-left: 5%;" method="GET" action="">
                                         <div class="input-group">
                                             <form method="GET" action="">
                                             <input type="text" class="form-control" placeholder="Search for other recipes" name="q">
                                             <div class="input-group-btn">
                                                 <button type="submit" class="btn btn-primary" value="Search">Search</button>
                                             </div>
                                             </form>
                                         </div>
                                         <li  class="btn btn-link" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                                         <a>filter</a>
                                         </li>
                                     </form>
                                 </div>

                                <ul class="nav navbar-nav navbar-right">


                                        <a href="{% url 'food:post_new' %}">New recipe</a>


                                 </ul>
                             </div>
                         </div>
                     </nav>

                     <div class="display"><p>result shows below:</p></div>
              {% for post in posts %}
              <img src="{{post.image.url}}">
<p><a href="/food/{{post.id}}"> {{post.title}}</a></p>

{% endfor %}


                     <div class="pos-f-t">
                       <div class="collapse" id="navbarToggleExternalContent">
                         <div class="bg-inverse p-4">
                           <h4 class="text-white">Collapsed content</h4>
                           <span class="text-muted">
                                       <div class="fil">
                                        <li class="disabled">Price</a></li>
                                        <li><a href="#">high to low</a></li>
                                        <li><a href="#">low to high</a></li>
                                      </div>
                                      <div class="fil">
                                        <li class="disabled">people</li>
                                        <li><a href="#"> 1-3 people</a></li>
                                        <li><a href="#"> more than 3 people </a></li>
                                      </div>
                                      <div class="fil">
                                        <li class="disabled">rating</a></li>
                                        <li><a href="#">most favorite</a></li>
                                        <li><a href="#">most comment</a></li>
                                      </div>
                         </div>
                       </div>

                     </div>



			<div class="container" id="items">
				<!-- <div class="foodItem col-md-4">Käse</div> -->
			</div>

</div>
</div>

    </body>
</html>

food/templates/food/post_edit.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title>upload of recipe </title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <!-- jQuery library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <!-- Latest compiled JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <!-- CSS file made by the group -->
        <link href="style-4.css" rel="stylesheet">
    </head>

    <body class="body4">





        <div class="container">
            <div class="col-lg-10 col-lg-offset-1">
                <nav class="navbar navbar-inverse ">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand"  href="FirstPage.html">Home</a>
                        </div>

                        <div class="collapse navbar-collapse" id="navbar-collapse-1">
                           <div class="hidden-sm col-md-5">
                                <form class="navbar-form navbar-left" style="margin-left: 5%;" method="GET" action="">
                                <div class="input-group">
                                      <input type="text" class="form-control" placeholder="Recipe..." name="q">
                                      <div class="input-group-btn">
                                            <button type="submit" class="btn btn-primary">Search</button>
                                      </div>
                                </div>
                                </form>
                            </div>
                      </div>
                 </div>
                  </nav>

      <div class="row" id="margin-top-10">

                 <div class="col-md-10 col-md-offset-1">
                     <div class="panel panel-default">
                         <div class="panel-body">
                             <h3 class="media-heading">your recipe</h3>

                             <form method="POST" class="post-form" enctype=multipart/form-data>
                                 {% csrf_token %}
                                 <div class="row">
                                     <div class="col-md-8">
                                         <div class="form-group">
                                             <label for="id_title">Title</label>
                                             {{form.title}}
                                         </div>
                                         <div class="form-group">
                                             <label for="id_image">Image</label>
                                             <div class="input-group">
                                                 <label class="input-group-btn">
                                                     <span class="btn btn-primary">
                                                         Browse&hellip; <input type="file" name="image" style="display: none;" onchange="$('#file-text').val($(this).val().replace('C:\\fakepath\\', ''));" required>
                                                     </span>
                                                 </label>
                                                 {{form.image}}
                                             </div>
                                         </div>

                                         <div class="form-group">
                                             <label for="id_description">Description</label>
                                             {{form.text}}
                                         </div>
                                     </div>
                                     <div class="col-md-4">
                                         <div class="form-group">

                                           <label>amount of people</label>
                                           {{form.people}}


                                          <label>budget</label>
                                            {{form.budget}}
                                         <label for="id_ingredients">Ingredients</label>
                                         <p>Please separate every ingredient with an enter.</p>
                                         {{form.ingredients}}



                                         </div>
                                     </div>
                                 </div>

                                 			<button type="submit" class="save btn btn-default">Save</button>

                             </form>
                         </div>
                     </div>
                 </div>

                                 </div>
                             </div>
                         </div>

<form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="save btn btn-default">Save</button>
		</form>

    </body>
</html>